"""targets PicleType

Revision ID: 1ce7549a018d
Revises: 8eebd7cdbdc0
Create Date: 2017-11-07 19:57:43.152004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ce7549a018d'
down_revision = '8eebd7cdbdc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sites', sa.Column('targets', sa.PickleType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sites', 'targets')
    # ### end Alembic commands ###
