"""campos PicleType ProdutoEncontrado

Revision ID: 44db4eb9577f
Revises: 1ce7549a018d
Create Date: 2017-11-07 19:59:03.038298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44db4eb9577f'
down_revision = '1ce7549a018d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produtosencontrados', sa.Column('campos', sa.PickleType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produtosencontrados', 'campos')
    # ### end Alembic commands ###
