"""param_names

Revision ID: ba84e6db3bcd
Revises: 44db4eb9577f
Create Date: 2017-11-14 14:30:01.438014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba84e6db3bcd'
down_revision = '44db4eb9577f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sites', sa.Column('params_names', sa.PickleType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sites', 'params_names')
    # ### end Alembic commands ###
